package org.gitlab4j.api;

public interface PropertyConstants {

    String TEST_PROJECT_SUBDIRECTORY_PATH = "src/main/docs/test-project.txt";

    // The following are keys used to look up values in the test properties file
    String ADMIN_PASSWORD_KEY = "TEST_ADMIN_PASSWORD";
    String ADMIN_USERNAME_KEY = "TEST_ADMIN_USERNAME";
    String ACCESS_TOKEN_KEY = "TEST_ACCESS_TOKEN";
    String BLOCK_USERNAME_KEY = "TEST_BLOCK_USERNAME";
    String GROUP_KEY = "TEST_GROUP";
    String GROUP_MEMBER_USERNAME_KEY = "TEST_GROUP_MEMBER_USERNAME";
    String GROUP_PROJECT_KEY = "TEST_GROUP_PROJECT";
    String HEALTH_CHECK_TOKEN_KEY = "TEST_HEALTH_CHECK_TOKEN";
    String HOST_URL_KEY = "TEST_HOST_URL";
    String LOGIN_PASSWORD_KEY = "TEST_LOGIN_PASSWORD";
    String LOGIN_USERNAME_KEY = "TEST_LOGIN_USERNAME";
    String NAMESPACE_KEY =  "TEST_NAMESPACE";
    String PRIVATE_TOKEN_KEY =  "TEST_PRIVATE_TOKEN";
    String PROJECT_NAME_KEY = "TEST_PROJECT_NAME";
    String PROXY_PASSWORD_KEY = "TEST_PROXY_PASSWORD";
    String PROXY_URI_KEY = "TEST_PROXY_URI";
    String PROXY_USERNAME_KEY = "TEST_PROXY_USERNAME";
    String SUB_GROUP_KEY = "TEST_SUB_GROUP";
    String SUDO_AS_USERNAME_KEY = "TEST_SUDO_AS_USERNAME";
    String TEST_REQUEST_ACCESS_USERNAME_KEY = "TEST_REQUEST_ACCESS_USERNAME";
    String USERNAME_KEY = "TEST_USERNAME";
    String XFER_NAMESPACE_KEY = "TEST_XFER_NAMESPACE";
    String EXTERNAL_PROVIDER_KEY = "TEST_EXTERNAL_PROVIDER";
    String EXTERNAL_UID_KEY = "TEST_EXTERNAL_UID";
    String EXTERNAL_USERNAME_KEY = "TEST_EXTERNAL_USERNAME";
}
